### ISSUE TITLE
Virkningstidspunkt må spesifiseres med tidssone

### ISSUE THREAD

**Issue by asjafjell** [difi/begrep-SikkerDigitalPost#170]
Hei,

Virkningstidspunkt må spesifiseres med tidssone også, for å ikke leveres på feil tidspunkt, eventuelt justeres til UTC/Z. 
<virkningstidspunkt> 2015-01-30T08:00:00.000+01:00 </virkningstidspunkt>

Det er også skrivefeil, for dere har virkningsdato som lukkende tag i xml.

**Comment by aberner** [comment]
takk, da har jeg forsøkt å fikse dette.
jeg ser fra eksemplet ditt at datoen er på format: 
15-01-30, mens jeg hadde forventet at århundre hadde blitt skrevet ut.
Derfor har jeg laget eksemplet slik:

2015-01-30T08:00:00.000+01:00

@asjafjell kan du bekrefte at det er ok før vi lukker saken.

**Comment by asjafjell** [comment]
Det var en skrivefeil at århundre ble utelatt. Jeg bekrefter at ny dokumentasjon er korrekt.

Takk for rask respons.
